### PR TITLE
nc-sa-2020-015.json: update 16.x comparison

### LINKED ISSUE #19976: nextcloud 16.0.10 release missing
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1. Read [nC-SA-2020-015](https://nextcloud.com/security/advisory/?id=nC-SA-2020-015)
2. Try to find Nextcloud Server 16.0.10, which should fix above issue
3. See it's missing from https://download.nextcloud.com/server/releases/

### Expected behaviour
It should be hosted there.

### Actual behaviour
It's currently not available.

### Server configuration
This is for packaging Nextcloud for the current (phasing out) stable distro release, so we'd like to keep the 16.x track

### PR DESCRIPTION
**Pull request by flokli**
Turns out, this was a typo, and this is already fixed in 16.0.9 by
https://github.com/nextcloud/server/pull/19362.

See https://github.com/nextcloud/server/issues/19976 for context.

Closes: https://github.com/nextcloud/server/issues/19976

### CODE REVIEW

**Review by kesselb — APPROVED** [review]

**Review by rullzer — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by flokli** [comment]
Thanks! Is there anything needed to redeploy the website? So far, it still shows the old version number.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/nextcloud.com/pull/1257

**Comment by nickvergessen** [comment]
It's now deployed, thanks for checking and proposing the fix!

**Comment by flokli** [comment]
Thanks!

**Pull request merged**
